site_name: My Docs
repo_url: https://github.com/A-Baji/mk-docs-main
repo_name: Multi docs prototype
theme: material

plugins:
  - multirepo:
      cleanup: false

nav:
  - Intro: 'index.md'
  - Repo 1: '!import https://github.com/A-Baji/mk-docs-sample1'
  - Repo 2: '!import https://github.com/A-Baji/mk-docs-sample2'
  - Repo 3: '!import https://github.com/A-Baji/mk-docs-sample3'
